## The server configuration
server:
  port: 9999
  servlet:
    context-path: /karate-web
  ssl:
    enabled: false

## database configuration
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:karate;MODE=Oracle;INIT=SET SCHEMA karate\;
    username: karate
    password: 1
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: MG_SCHEMA_HISTORY
    user: karate
    password: 1
    url: jdbc:h2:mem:karate;MODE=Oracle;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS karate\; CREATE USER IF NOT EXISTS karate PASSWORD '1'\;SET SCHEMA karate\;
  h2:
    console:
      ## the console should be http://hostname:port/contextPath/h2-console/
      enabled: true
  profiles:
    active: local


## Karate web
karate-web:
  engine:
    thread-count: 1
  report:
    home: ${REPORT_HOME}
    context-path: report

